name: machine-learning-cfr
channels:
  - defaults
dependencies:
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.54.1
      - imbalanced-learn==0.12.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - numpy==2.1.2
      - nvidia-nccl-cu12==2.23.4
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.0.0
      - pyparsing==3.2.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - threadpoolctl==3.5.0
      - tzdata==2024.2
      - xgboost==2.1.2
